---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  #- name: debian-8.1
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[carton::default]
      - recipe[test]
    attributes:
