---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-5.11

suites:
  - name: default
    run_list:
      - recipe[carton::default]
      - recipe[test]
    attributes:
